package com.dataobject.entity;

public class UserPassword {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_password.ID
     *
     * @mbg.generated Thu Mar 05 17:48:57 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_password.USER_ID
     *
     * @mbg.generated Thu Mar 05 17:48:57 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_password.USER_PASSWORD
     *
     * @mbg.generated Thu Mar 05 17:48:57 CST 2020
     */
    private String userPassword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_password.ID
     *
     * @return the value of user_password.ID
     *
     * @mbg.generated Thu Mar 05 17:48:57 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_password.ID
     *
     * @param id the value for user_password.ID
     *
     * @mbg.generated Thu Mar 05 17:48:57 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_password.USER_ID
     *
     * @return the value of user_password.USER_ID
     *
     * @mbg.generated Thu Mar 05 17:48:57 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_password.USER_ID
     *
     * @param userId the value for user_password.USER_ID
     *
     * @mbg.generated Thu Mar 05 17:48:57 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_password.USER_PASSWORD
     *
     * @return the value of user_password.USER_PASSWORD
     *
     * @mbg.generated Thu Mar 05 17:48:57 CST 2020
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_password.USER_PASSWORD
     *
     * @param userPassword the value for user_password.USER_PASSWORD
     *
     * @mbg.generated Thu Mar 05 17:48:57 CST 2020
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }
}