package com.example.entity;

import com.example.utils.page.PageVo;

public class User  {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.ID
     *
     * @mbg.generated Thu Mar 05 17:48:57 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.NAME
     *
     * @mbg.generated Thu Mar 05 17:48:57 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.GENDER
     *
     * @mbg.generated Thu Mar 05 17:48:57 CST 2020
     */
    private Boolean gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.PHONE
     *
     * @mbg.generated Thu Mar 05 17:48:57 CST 2020
     */
    private String phone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.ID
     *
     * @return the value of sys_user.ID
     *
     * @mbg.generated Thu Mar 05 17:48:57 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.ID
     *
     * @param id the value for sys_user.ID
     *
     * @mbg.generated Thu Mar 05 17:48:57 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.NAME
     *
     * @return the value of sys_user.NAME
     *
     * @mbg.generated Thu Mar 05 17:48:57 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.NAME
     *
     * @param name the value for sys_user.NAME
     *
     * @mbg.generated Thu Mar 05 17:48:57 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.GENDER
     *
     * @return the value of sys_user.GENDER
     *
     * @mbg.generated Thu Mar 05 17:48:57 CST 2020
     */
    public Boolean getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.GENDER
     *
     * @param gender the value for sys_user.GENDER
     *
     * @mbg.generated Thu Mar 05 17:48:57 CST 2020
     */
    public void setGender(Boolean gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.PHONE
     *
     * @return the value of sys_user.PHONE
     *
     * @mbg.generated Thu Mar 05 17:48:57 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.PHONE
     *
     * @param phone the value for sys_user.PHONE
     *
     * @mbg.generated Thu Mar 05 17:48:57 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }
}